- name: mysql-databases | Remove test database
  mysql_db: name=test state=absent
- name: Ensure anonymous users are not in the database
  mysql_user: user='' host=$item state=absent
  with_items:
        - 127.0.0.1
        - ::1
        - localhost

- name: mysql-databases | Create OpenMRS database
  mysql_db:
    name: "{{ openmrs_db_name }}"
    encoding: "utf8"
    collation: "utf8_general_ci"
    login_user: "root"
    login_password: "{{ openmrs_db_root_password }}"

- name: mysql-databases | Create database user with full access to the OpenMRS db
  mysql_user:
    name: "{{ openmrs_db_user }}"
    password: "{{ openmrs_db_password }}"
    priv: "{{ openmrs_db_name }}.*:ALL"
    login_user: "root"
    login_password: "{{ openmrs_db_root_password }}"