---
- name: Remove test databases
  mysql_db:
    name: test
    state: absent

- name: Remove anonymous users
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: Set root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create Moodle database
  mysql_db:
    name: elearningdb
    state: present

- name: Create Moodle user
  mysql_user:
    name: elearninguser
    password: "{{ moodle_user_password }}"
    priv: "elearningdb.*:ALL"
    state: present
