---
- hosts: all
  become: yes
  gather_facts: false
  vars_files:
      - ../vars/all_vars.yml
- name: Install Canvas LMS on Ubuntu 20.04 LTS
  #  hosts: your_target_hosts # Replace with the appropriate hosts or groups from your inventory
  #become: yes
  roles:
    - canvas_lms
    - canvas_db

