- name: Install maintenance Parent cron
  hosts: all
  become: yes
  vars_files:
      - ../vars/maintenance-vars-east.yml

  tasks:
   - name: "run parent script"
     ansible.builtin.cron:
      name: "run parent script"
      user: "{{ maintenance_cron_user }}"
      state: present
      minute: "0"
      hour: "*/6"
      day: "*"
      month: "*"
      weekday: "*"
      job: '/home/openmrs_maintenance_rwanda/maintenance/tools/parent/master_parent_script.sh'