- hosts: all
  become: yes
  gather_facts: false
  vars_files:
      - ../vars/maintenance-vars-east.yml

  tasks:
  - group: name={{ maintenance_group_name }} state=present

  - user: name={{  maintenance_username }} password={{ maintenance_password }} home={{ maintenance_home_dir }} group={{ maintenance_group_name }} shell=/bin/bash

  - lineinfile: dest=/etc/sudoers state=present line='{{ maintenance_username }} ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'

  - name: Maintance Tool | create .ssh dir
    file: path={{ maintenance_home_dir }}/.ssh state=directory owner={{  maintenance_username }} mode=0700

  - copy: src=roles/rwanda-maintenance/files/authorized_keys dest={{ maintenance_home_dir }}/.ssh owner={{ maintenance_username }} mode=0644

  - name: Maintance Tool | Remove "{{ maintenance_home_dir }}/maintenance" (git will re-create this folder)
    command: rm -rf {{ maintenance_home_dir }}/maintenance

  - git:
      repo: "{{ maintenance_git_url }}"
      dest: "{{ maintenance_home_dir }}/maintenance"

  - name: Creates directories
    file:
      path: "{{ maintenance_home_dir }}/maintenance/{{ item }}"
      state: directory
      owner:  "{{ maintenance_username }}"
    with_items:
       - openmrs_modules
       - openmrs_war
       - other_files
       - trusted_sql

  - name: Maintance Tool | Remove "{{ maintenance_home_dir }}/maintenance/playbook"
    command: rm -rf {{ maintenance_home_dir }}/maintenance/playbook

  - name: Maintance Tool | Remove "{{ maintenance_home_dir }}/maintenance/README.md"
    command: rm -rf {{ maintenance_home_dir }}/maintenance/README.md

  - name: Maintance Tool | Remove git dir
    command: rm -rf {{ maintenance_home_dir }}/maintenance/.git

  - name: Maintance Tool | Remove gitignore file
    command: rm -rf {{ maintenance_home_dir }}/maintenance/.gitignore

  - name: Maintance Tool | Ensure "{{ maintenance_home_dir }}" has the correct ownership
    command: chown -R {{  maintenance_username }}:{{  maintenance_username }} {{ maintenance_home_dir }}